import { Page } from './types';
import { brand } from '@/config/brand';

export const mockPages: Page[] = [
  {
    id: 'page-1',
    slug: 'about',
    title: `What is ${brand.name}?`,
    sections: [
      {
        id: 'sec-1',
        pageId: 'page-1',
        name: 'Hero/Intro',
        content: `${brand.name} is a digital marketplace connecting shoppers, merchants, and communities across Nigeria. Discover local products, grow your business, and earn rewards for helping the ecosystem thrive.`,
        order: 1,
        status: 'Published',
        version: 1,
      },
      {
        id: 'sec-2',
        pageId: 'page-1',
        name: 'Shop (For Customers)',
        content: 'Discover products and services from businesses around Nigeria. Quality local goods, delivered to you.',
        order: 2,
        status: 'Published',
        version: 1,
      },
      {
        id: 'sec-3',
        pageId: 'page-1',
        name: 'Sell (For Merchants)',
        content: 'Put your business in front of more customers, manage your digital storefront, and scale your operations.',
        order: 3,
        status: 'Published',
        version: 1,
      },
      {
        id: 'sec-4',
        pageId: 'page-1',
        name: 'Earn (For Members)',
        content: 'Refer friends, participate in the community, and earn commissions through our rewards program.',
        order: 4,
        status: 'Published',
        version: 1,
      },
    ],
  },
  {
    id: 'page-2',
    slug: 'community',
    title: 'Community',
    sections: [
      {
        id: 'sec-5',
        pageId: 'page-2',
        name: 'Hero',
        content: 'Join the community and build your network.',
        order: 1,
        status: 'Published',
        version: 1,
      },
      {
        id: 'sec-6',
        pageId: 'page-2',
        name: 'How the hierarchy works',
        content: 'Our hierarchy structure consists of multiple levels where you earn commissions on direct referrals and team sales. Build your downline to increase your network share.',
        order: 2,
        status: 'Published',
        version: 1,
      },
      {
        id: 'sec-7',
        pageId: 'page-2',
        name: 'Purchasing advantages',
        content: 'As a community member, you gain access to exclusive discounts, early access to sales, and special promotional offers from top verified merchants.',
        order: 3,
        status: 'Published',
        version: 1,
      },
      {
        id: 'sec-8',
        pageId: 'page-2',
        name: 'Earning',
        content: 'Earn direct commissions on sales from your referrals, and gather reward points on your activities and reviews. (Rates are subject to the active commission plan).',
        order: 4,
        status: 'Published',
        version: 1,
      },
      {
        id: 'sec-9',
        pageId: 'page-2',
        name: 'FAQ',
        content: 'Q: How do I join? A: Simply click Join below.\\nQ: Do I need to pay to join? A: Registration is free.\\nQ: How do I share my link? A: Once registered, your referral code will be available in your portal.',
        order: 5,
        status: 'Published',
        version: 1,
      },
      {
        id: 'sec-10',
        pageId: 'page-2',
        name: 'Call to action',
        content: 'Ready to start earning?',
        order: 6,
        status: 'Published',
        version: 1,
      }
    ],
  },
];
