import { Button } from '@/components/ui/button';
import Image from 'next/image';

export function RewardsProgramPromo() {
  return (
    <section className="py-20 bg-white border-y border-border">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="flex flex-col md:flex-row items-center gap-16">
          <div className="flex-1 space-y-8">
            <div className="space-y-4 animate-in slide-in-from-left-4 duration-700">
              <span className="inline-block py-1 px-3 rounded-full bg-[#fff9f0] text-copper text-xs font-bold tracking-widest uppercase border border-[#f5e6d3]">
                Rewards Program
              </span>
              <h2 className="text-3xl md:text-4xl font-extrabold text-brand-900 tracking-tight">
                Shop. Refer. Earn. Grow.
              </h2>
              <p className="text-lg text-text-muted">
                Turn your network into an opportunity. Refer people to ABA Online, help local businesses reach more customers, and earn commissions through our community-driven rewards program.
              </p>
            </div>

            <div className="space-y-6">
              {[
                { step: '01', title: 'Join', desc: 'Create your free ABA Online account.' },
                { step: '02', title: 'Share', desc: 'Invite customers, businesses, or members to the platform.' },
                { step: '03', title: 'Earn', desc: 'Receive eligible commissions on sales generated by your network.' },
                { step: '04', title: 'Grow', desc: 'Build your network and unlock more leadership opportunities.' },
              ].map((s, i) => (
                <div key={i} className="flex gap-4 group cursor-default">
                  <div className="w-10 h-10 rounded-full bg-brand-50 flex items-center justify-center text-brand-600 font-bold shrink-0 group-hover:bg-brand-600 group-hover:text-white group-hover:scale-110 transition-all duration-300">{s.step}</div>
                  <div>
                    <h4 className="font-bold text-text text-lg group-hover:text-brand-600 transition-colors duration-300">{s.title}</h4>
                    <p className="text-text-muted group-hover:text-text transition-colors duration-300">{s.desc}</p>
                  </div>
                </div>
              ))}
            </div>

            <Button size="lg" className="bg-copper hover:bg-[#a67732] text-white rounded-full font-bold px-8 hover:scale-105 hover:shadow-lg hover:shadow-copper/20 transition-all duration-300">
              Learn How It Works &rarr;
            </Button>
          </div>

          <div className="flex-1 w-full relative">
            <div className="aspect-square bg-surface-2 border border-border overflow-hidden relative shadow-inner flex items-center justify-center ">
              <Image width={500} height={500} src="/aba-illustration.png" alt="" className='w-full h-full' />
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
